name = "majibattle"
main = "dist/index.js"
compatibility_date = "2024-01-01"

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Staging environment for PR previews
[env.staging]
name = "majibattle-staging"

[[env.staging.durable_objects.bindings]]
name = "GAME_SESSION"
class_name = "GameSessionV3"

[[env.staging.migrations]]
tag = "v3-staging"
new_sqlite_classes = [ "GameSessionV3" ]

# Production environment
[env.production]
name = "majibattle"

[[env.production.durable_objects.bindings]]
name = "GAME_SESSION"
class_name = "GameSessionV3"

[[env.production.migrations]]
tag = "v3-production"
new_sqlite_classes = [ "GameSessionV3" ]

# Build settings
[build]
command = "npm run build"

# Durable Objects configuration
# Default environment uses GameSessionV3 to avoid conflicts with existing production instances
[[durable_objects.bindings]]
name = "GAME_SESSION"
class_name = "GameSessionV3"

# Migration for new GameSessionV3 class (safe because it's a new class)
[[migrations]]
tag = "v3"
new_sqlite_classes = [ "GameSessionV3" ]

# Note: All environments now use versioned classes to avoid SQLite migration conflicts

# Environment variables
[vars]
GEMINI_MODEL = "gemini-2.5-flash-lite-preview-06-17"

# Secret bindings (use wrangler secret put GEMINI_API_KEY)
# For local development: create .dev.vars file with GEMINI_API_KEY=your-key
