name = "majibattle"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Staging environment for PR previews
[env.staging]
name = "majibattle-staging"

# Production environment
[env.production]
name = "majibattle"

# Build settings
[build]
command = "npm run build"

# Durable Objects configuration
[[durable_objects.bindings]]
name = "GAME_SESSION"
class_name = "GameSession"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = [ "GameSession" ]
