name: Playwright E2E Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Volta environment
        run: |
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"
          echo "VOLTA_HOME=$VOLTA_HOME" >> $GITHUB_ENV
          echo "$VOLTA_HOME/bin" >> $GITHUB_PATH

      - name: Cache node_modules
        uses: corca-ai/local-cache@v2
        with:
          path: node_modules
          key: deps-e2e-${{ hashFiles('package-lock.json') }}
          base: /tmp/cache
        continue-on-error: true

      - name: Install dependencies
        run: npm ci

      - name: Setup Playwright browser cache
        run: |
          # Set up local playwright cache directory
          export PLAYWRIGHT_BROWSERS_PATH="$HOME/.cache/playwright-browsers"
          echo "PLAYWRIGHT_BROWSERS_PATH=$PLAYWRIGHT_BROWSERS_PATH" >> $GITHUB_ENV
          mkdir -p "$PLAYWRIGHT_BROWSERS_PATH"

      - name: Check if Playwright browsers exist locally
        id: check-browsers
        run: |
          if [ -d "$PLAYWRIGHT_BROWSERS_PATH/chromium-"* ]; then
            echo "browsers-exist=true" >> $GITHUB_OUTPUT
            echo "Playwright browsers already installed in $PLAYWRIGHT_BROWSERS_PATH"
          else
            echo "browsers-exist=false" >> $GITHUB_OUTPUT
            echo "Playwright browsers not found, will install"
          fi

      - name: Install Playwright browsers
        if: steps.check-browsers.outputs.browsers-exist == 'false'
        run: |
          # Install only chromium browser without system dependencies
          # This avoids sudo requirements on self-hosted runners
          npx playwright install chromium --dry-run || true
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0 npx playwright install chromium || {
            echo "Failed to install Playwright browsers, attempting manual download..."
            # Fallback: manually download if automated install fails
            npx playwright install-deps chromium || echo "Dependency installation skipped (requires sudo)"
            npx playwright install chromium
          }

      - name: Build project for E2E
        run: npm run build

      - name: Kill any existing processes on port 8787
        run: |
          # Kill any process using port 8787 without sudo
          # First try lsof which doesn't require sudo
          if command -v lsof >/dev/null 2>&1; then
            lsof -ti:8787 | xargs -r kill -9 || true
          else
            # Fallback to fuser without sudo (may not work on all systems)
            fuser -k 8787/tcp 2>/dev/null || true
          fi
          # Wait a moment for cleanup
          sleep 2

      - name: Run Playwright E2E tests
        run: npm run test:e2e
        env:
          CI: true
          PLAYWRIGHT_BROWSERS_PATH: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-${{ github.run_id }}
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-results-${{ github.run_id }}
          path: test-results/
          retention-days: 7